container:
  image: kitware:cmake
  cpu: 8

task:
  name: Build new_scf
  install_dependencies_script:
    - apt-get update
    - apt-get install -y openblas
  configure_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++
    - cd ..

  make_script:
    - cd build
    - make -j4
